# Generated by Django 3.2.4 on 2021-06-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_key', models.CharField(help_text='MD5 hash of the file', max_length=50, unique=True)),
                ('original_meta_data', models.TextField(null=True)),
                ('original_size', models.IntegerField(help_text='The size, in bytes, of the uploaded file.', null=True)),
                ('original_charset', models.CharField(max_length=255, null=True)),
                ('bucket_name', models.CharField(max_length=255, null=True)),
                ('server_reply', models.TextField(null=True)),
                ('image_width', models.IntegerField(help_text='Width if the file is image', null=True)),
                ('image_height', models.IntegerField(help_text='Height if the file is image', null=True)),
                ('image_average_color', models.CharField(help_text='image average color', max_length=7, null=True)),
            ],
            options={
                'db_table': 'biztyz_db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileTransactionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(null=True)),
                ('original_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'biztyz_db',
                'managed': False,
            },
        ),
    ]
