version: '3'  

services:
    postgres:
        image: postgis/postgis:12-master
        environment:
            - POSTGRES_DB: ci
            - POSTGRES_USER: postgres
            - POSTGRES_PASSWORD: postgres
            - POSTGRES_HOST_AUTH_METHOD: trust
    web:
        build: .
        environment:
            - SENDGRID_API_KEY: $SENDGRID_API_KEY 
            - GCP_USER: $GCP_USER
            - GCP_SECRET: $GCP_SECRET
            - GCP_BUCKET: $GCP_BUCKET
        command: bash -c "DJANGO_ENV=staging python manage.py makemigrations && python manage.py migrate && gunicorn -w 1 --bind 0.0.0.0:8000 server.wsgi"
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - postgres
    nginx:
        build: ./config/nginx
        container_name: ng_server
        depends_on:
            - web
        command: nginx -g 'daemon off;'
        ports:
            - "80:80"
        volumes:
            - ./static:/var/www/static